spring:
  application:
    name: 'jwtauth'

  flyway:
    enabled: true
    locations: classpath:db/migrations/default/postgres

  datasource:
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${PG_PORT}/auth_db
    hikari:
      auto-commit: false
springdoc:
  swagger-ui:
    path: /swagger
