spring:
  application:
    name: 'jwtauth'

  flyway:
    enable: true
    location: 'db/migrations/default/postgres'

  datasource:
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/authentication_db'
    hikari:
      auto-commit: false
