spring:
  application:
    name: 'jwtauth'

  flyway:
    enable: true
    location: 'db/migrations/default/postgres'

  datasource:
    username: postgres
    password: '###hashtag###'
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:9000/auth_db'
    hikari:
      auto-commit: false
springdoc:
  swagger-ui:
    path: /swagger
