spring:
  application:
    name: 'oauth2'
  security:
    oauth2:
      resourceserver:
        jwt:
          trusted-issuers:
            - ${OAUTH2_JWT_GOOGLE_ISSUER:blank}
            - ${OAUTH2_JWT_APPLE_ISSUER:blank}
        opaquetoken:
          servers:
            - introspection-uri: ${OAUTH2_S1_OT_INTROSPECTION_URI:blank}
              client-id: ${OAUTH2_S1_OT_CLIENT_ID:blank}
              client-secret: ${OAUTH2_S1_OT_CLIENT_SECRET:blank}
              name: ${OAUTH2_S1_OT_NAME:blank}

  flyway:
    enabled: true
    locations: classpath:db/migrations/default/postgresql
    schemas: [ public ]

  datasource:
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${PG_PORT}/auth_db
    hikari:
      auto-commit: false
springdoc:
  swagger-ui:
    path: /swagger